// <auto-generated />
using System;
using DashboardPanel.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashboardPanel.Migrations
{
    [DbContext(typeof(GrafikDbContext))]
    [Migration("20220627164552_initialGrafik")]
    partial class initialGrafik
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DashboardPanel.Entities.Grafik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Grafiks");
                });

            modelBuilder.Entity("DashboardPanel.Entities.GrafikData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anahtar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrafikId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GrafikId");

                    b.ToTable("GrafikDatas");
                });

            modelBuilder.Entity("DashboardPanel.Entities.GrafikData", b =>
                {
                    b.HasOne("DashboardPanel.Entities.Grafik", "Grafik")
                        .WithMany()
                        .HasForeignKey("GrafikId");

                    b.Navigation("Grafik");
                });
#pragma warning restore 612, 618
        }
    }
}
